site_name: Shinzen Young - Talks on Teaching
site_url: https://stillpoint.github.io/talksonteaching
theme:
  name: material
nav:
    - Disc 1 - Track 1: disc1track1.md
    - Disc 1 - Track 2: disc1track2.md
    - Disc 2 - Track 1: disc2track1.md
    - Disc 3 - Track 1: disc3track1.md
    - Disc 4 - Track 1: disc4track1.md
    - Disc 4 - Track 2: disc4track2.md
    - Disc 4 - Track 3: disc4track3.md
    - Disc 5 - Track 1: disc5track1.md
    - Disc 5 - Track 2: disc5track2.md
    - Disc 6 - Track 1: disc6track1.md
    - Disc 7 - Track 1: disc7track1.md
    - Disc 7 - Track 2: disc7track2.md
    - Disc 8 - Track 1: disc8track1.md
    - Disc 8 - Track 2: disc8track2.md
plugins:
    - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true